Allow initialization of the cluster from backups
Currently, replica's will already use the S3 backups if they are
available to create a $PGDATA directory.
However, if no master (endpoint) is available, the behaviour up to now
was to always do an initdb.

This may not be what the user wants, say - a user wants to suspend a
service - removing all the Kubernetes objects and only keeping the S3
backups.

In such a scenario, it would be great if the backup would be used to
initialize the whole cluster.

Addresses GitHub issue #134

diff --git a/charts/timescaledb-single/templates/configmap-scripts.yaml b/charts/timescaledb-single/templates/configmap-scripts.yaml
--- a/charts/timescaledb-single/templates/configmap-scripts.yaml
+++ b/charts/timescaledb-single/templates/configmap-scripts.yaml
@@ -96,24 +96,105 @@ data:
     source "{{ template "pod_environment_file" }}"
 
     function log {
-      echo "$(date '+%Y-%m-%d %H:%M:%S') - restore_or_initdb - $1"
+        echo "$(date '+%Y-%m-%d %H:%M:%S') - restore_or_initdb - $1"
     }
 
     PGDATA={{ include "data_directory" . | quote }}
     WALDIR={{ include "wal_directory" . | quote }}
+    # A missing PGDATA points to Patroni removing a botched PGDATA, or manual
+    # intervention. In this scenario, we need to recreate the DATA and WALDIRs
+    # to keep pgBackRest happy
+    [ -d "${PGDATA}" ] || install -o postgres -g postgres -d -m 0700 "${PGDATA}"
+    [ -d "${WALDIR}" ] || install -o postgres -g postgres -d -m 0700 "${WALDIR}"
 
-    # Patroni attaches --scope and --datadir to the arguments, we need to strip them off as
-    # initdb has no business with these parameters
-    initdb_args=""
-    for value in "$@"
-    do
-      [[ $value == --scope* ]] || [[ $value == --datadir* ]] || initdb_args="${initdb_args} $value"
-    done
+    if [ "${BOOTSTRAP_FROM_BACKUP}" == "1" ]; then
+        log "Attempting restore from backup"
+        # we want to override the environment with the environment
+        export $(env -i envdir {{ template "pgbackrest_bootstrap_environment_dir" . | quote }} env) > /dev/null
+        export PGBACKREST_REPO1_PATH={{ index .Values.bootstrapFromBackup "repo1-path" | quote }}
 
-    log "Invoking initdb"
-    initdb --auth-local=peer --auth-host=md5 --pgdata="${PGDATA}" --waldir="${WALDIR}" ${initdb_args}
+        if [ "${PGBACKREST_REPO1_PATH}" == "" ]; then
+            log "Unconfigured repository path"
+            cat << "__EOT__"
+
+    TimescaleDB Single Helm Chart error:
+
+    You should configure the bootstrapFromBackup in your Helm Chart section by explicitly setting
+    the repo1-path to point to the backups.
+
+    For example, if you want to do a disaster recovery, and you want to reuse
+    the backup, you could configure the path as follows:
+
+    ```yaml
+    bootstrapFromBackup:
+      enabled: true
+      repo1-path: {{ (printf "/%s/%s/" .Release.Namespace (include "clusterName" . )) | quote }}
+    ```
+
+    For more information, consult the admin guide:
+    https://github.com/timescale/timescaledb-kubernetes/blob/master/charts/timescaledb-single/admin-guide.md#bootstrap-from-backup
+
+
+    __EOT__
+
+            exit 1
+        fi
+
+        log "Listing available backup information"
+        pgbackrest info
+        EXITCODE=$?
+        if [ "${EXITCODE}" != "0" ]; then
+            exit $EXITCODE
+        fi
+
+        pgbackrest --log-level-console=detail restore
+        EXITCODE=$?
+        if [ "${EXITCODE}" == "0" ]; then
+            log "pgBackRest restore finished succesfully, starting instance in recovery"
+            # We want to ensure we do not overwrite a current backup repository with archives, therefore
+            # we block archiving from succeeding until Patroni can takeover
+            touch "${PGDATA}/recovery.signal"
+            pg_ctl -D "${PGDATA}" start -o '--archive-command=/bin/false'
+
+            while ! pg_isready -q; do
+                log "Waiting for PostgreSQL to become available"
+                sleep 3
+            done
+
+            # It is not trivial to figure out to what point we should restore, pgBackRest
+            # should be fetching WAL segments until the WAL is exhausted. We'll ask pgBackRest
+            # what the Maximum Wal is that it currently has; as soon as we see that, we can consider
+            # the restore to be done
+            while true; do
+              MAX_BACKUP_WAL="$(pgbackrest info --output=json | python3 -c "import json,sys;obj=json.load(sys.stdin); print(obj[0]['archive'][0]['max']);")"
+              log "Testing whether WAL file ${MAX_BACKUP_WAL} has been restored ..."
+              [ $(find "${PGDATA}/pg_wal/${MAX_BACKUP_WAL}" -type f) ] && break;
+              sleep 30;
+            done
+
+            # At this point we know the final WAL archive has been restored, we should be done.
+            log "The WAL file ${MAX_BACKUP_WAL} has been successully restored, shutting down instance"
+            pg_ctl -D "${PGDATA}" promote
+            pg_ctl -D "${PGDATA}" stop -m fast
+            log "Handing over control to Patroni ..."
+        else
+            log "Bootstrap from backup failed"
+            exit 1
+        fi
+    else
+        # Patroni attaches --scope and --datadir to the arguments, we need to strip them off as
+        # initdb has no business with these parameters
+        initdb_args=""
+        for value in "$@"
+        do
+            [[ $value == --scope* ]] || [[ $value == --datadir* ]] || initdb_args="${initdb_args} $value"
+        done
+
+        log "Invoking initdb"
+        initdb --auth-local=peer --auth-host=md5 --pgdata="${PGDATA}" --waldir="${WALDIR}" ${initdb_args}
+    fi
+
     echo "include_if_exists = '{{ template "tstune_config". }}'" >> "${PGDATA}/postgresql.conf"
-
   post_init.sh: |
     #!/bin/bash
     source "{{ template "pod_environment_file" }}"
