Add ability to run custom post_init scripts
Co-authored-by: Esteban <invernizzie@users.noreply.github.com>
Co-authored-by: depeele <Elmo.Peele@gmail.com>

diff --git a/charts/timescaledb-single/templates/configmap-scripts.yaml b/charts/timescaledb-single/templates/configmap-scripts.yaml
--- a/charts/timescaledb-single/templates/configmap-scripts.yaml
+++ b/charts/timescaledb-single/templates/configmap-scripts.yaml
@@ -332,7 +332,49 @@ data:
     __SQL__
     done
 
-    # We always exit 0 this script, otherwise the database initialization fails.
+    # This directory may contain user defined post init steps
+    for file in {{ template "post_init_dir" . | quote }}/*
+    do
+      [ -d "$file" ] && continue
+      [ ! -r "$file" ] && continue
+
+      case "$file" in
+        *.sh)
+          if [ -x "$file" ]; then
+            log "Call post init script [ $file ]"
+            "$file" "$@"
+            EXITCODE=$?
+          else
+            log "Source post init script [ $file ]"
+            . "$file"
+            EXITCODE=$?
+          fi
+          ;;
+        *.sql)
+          log "Apply post init sql [ $file ]"
+          # Disable synchronous_commit since we're initializing
+          PGOPTIONS="-c synchronous_commit=local" psql -d "$URL" -f "$file"
+          EXITCODE=$?
+          ;;
+        *.sql.gz)
+          log "Decompress and apply post init sql [ $file ]"
+          gunzip -c "$file" | PGOPTIONS="-c synchronous_commit=local" psql -d "$URL"
+          EXITCODE=$?
+          ;;
+        *)
+          log "Ignore unknown post init file type [ $file ]"
+          EXITCODE=0
+          ;;
+      esac
+        EXITCODE=$?
+        if [ "$EXITCODE" != "0" ]
+        then
+            log "ERROR: post init script $file exited with exitcode $EXITCODE"
+            exit $EXITCODE
+        fi
+    done
+
+    # We exit 0 this script, otherwise the database initialization fails.
     exit 0
   patroni_callback.sh: |
     #!/bin/sh
